version: "3.7"

services:
  pidroid:
    restart: always
    image: pidroid-bot:latest
    container_name: pidroid
    volumes:
      - ./data:/app/data
    env_file:
      - config.env
    depends_on:
      - migration
      - db

  migration:
    build: .
    image: pidroid-bot:latest
    command: alembic upgrade head
    env_file:
      - config.env
    depends_on:
      - db

  # It is not recommended to expose anything to the outside world
  db:
    image: postgres:15-bullseye
    restart: always
    env_file:
      - config.env
    expose:
      - "5432"
    volumes: 
      - ./db_data:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
