[project]
name = "pidroid-bot"
requires-python = ">= 3.12"

[tool.mypy]
exclude = [
    "venv", 
    "alembic",
    "data",
    ".venv"
]

[tool.basedpyright]
reportMissingTypeStubs = false
pythonVersion = "3.12"
